app/__init__.py
#!/bin/python3
from flask import Flask, render_template
import os
import logging

logging.basicConfig(level=logging.INFO)

##########

here = os.path.abspath(os.path.dirname(__file__))
logging.info(f"Path exists: {os.path.exists(os.path.join(here, '.env'))}")


def create_app():
    app = Flask(__name__)

    @app.errorhandler(404)
    def page_not_found(e):
        return render_template("404.html"), 404

    # Register blueprints
    from app.routes import bp as main_routes

    app.register_blueprint(main_routes)

    ### - Miles tracker
    from app.miles import bp as miles

    app.register_blueprint(miles, url_prefix="/miles")

    ### - Food diary
    from app.food import bp as food

    app.register_blueprint(food, url_prefix="/foodLog")

    ### - Housing
    # from app.housing import bp as housing

    # app.register_blueprint(housing, url_prefix="/housing")

    return app

app/food/__init__.py
from flask import Blueprint

bp = Blueprint("food", __name__)

from app.food import routes

app/food/routes.py
from flask import render_template, redirect, request
from datetime import datetime
from app.food import bp
from app.food.helpers import get_all_diary_entries, read_manifest

###########


@bp.route("/", methods=["GET"])
def fd_landing():
    entries = get_all_diary_entries()
    return render_template("food_diary/index.html", entries=entries)


@bp.route("/day/<date_stamp>", methods=["GET"])
def log(date_stamp: str):
    """
    About
    """

    items = read_manifest(date_string=date_stamp, log_sql=False)
    clean_day = datetime.strptime(date_stamp, "%Y-%m-%d").strftime("%A %B %d, %Y")
    food = items["food"]
    counts = items["count"]

    return render_template(
        "food_diary/entry.html", items=zip(food, counts), clean_day=clean_day
    )


@bp.route("/viewAllLogs", methods=["GET"])
def log_all_days():
    """
    About
    """

    items = read_manifest(log_sql=False)
    clean_day = "every damn day"
    food = items["food"]
    counts = items["count"]

    return render_template(
        "food_diary/entry.html", items=zip(food, counts), clean_day=clean_day
    )

app/housing/__init__.py
from flask import Blueprint

bp = Blueprint("global", __name__)

from app.housing import routes

app/housing/routes.py
from flask import render_template, redirect, url_for
import logging

from app.housing import bp
from app.housing.helpers import get_rendered_map, isolate_values, build_map

logging.basicConfig(level=logging.INFO)

##########


@bp.route("/", methods=["GET", "POST"])
def index():
    """
    Main landing page for the housing routes
    """

    return render_template("housing/index.html")


@bp.route("/global_map", methods=["GET"])
def global_map():
    return render_template("housing/map__global.html")


@bp.route("/render/<year>", methods=["GET", "POST"])
def year(year: str):
    """
    Template route for each housing entry
    """

    packet = isolate_values(year=year)
    map_path = get_rendered_map()

    return render_template("housing/render.html", packet=packet, map_path=map_path)


@bp.route("/build_map", methods=["GET", "POST"])
def create_map_from_scratch():
    logging.info("Creating global map from scratch...")
    build_map()

    return redirect(url_for("main.index"))

app/miles/__init__.py
from flask import Blueprint

bp = Blueprint("miles", __name__)

from app.miles import routes

app/miles/routes.py
#!/bin/python3
from flask import render_template
from app.miles import bp

##########


@bp.route("/", methods=["GET", "POST"])
def index():
    return "Hello World"

app/routes/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__)

from app.routes import routes

app/routes/routes.py
from flask import render_template, request
import logging
from time import sleep
from datetime import datetime

from app.routes import bp
from app.common.twilio import receive_request

logging.basicConfig(level=logging.INFO)

##########


@bp.route("/", methods=["GET", "POST"])
@bp.route("/home", methods=["GET", "POST"])
def index():
    return render_template("index.html")


@bp.route("/acadmic_projects", methods=["GET"])
def academics():
    return render_template("academics.html")


@bp.route("/sms", methods=["POST"])
def sms():
    """This endpoint will receive incoming SMS POST requests from Twilio"""

    # receive_request()
    sent_to = request.form["To"]
    sent_from = request.form["From"]
    sent_body = request.form["Body"]
    current_time = datetime.now()

    try:
        receive_request(to=sent_to, from_=sent_from, body=sent_body, time=current_time)
        return "Success"

    except Exception as e:
        logging.error(e)
        return "Failure"


@bp.route("/rebuild_twilio", methods=["GET", "POST"])
def rebuild_twilio():
    from app.dev.twilio_rebuild import main as rebuild

    # Trigger sync from Twilio to BigQuery
    rebuild()

    return "Success"

app/templates/academics.html
<html>
{% extends "base.html" %}

<body>
    {% block content %}
    <div class="wrapper">
        <h1>Selected Academic Works</h1>
        <!-- GLM Express -->
        <div class="ac_project_box" style="margin-top: 0;">
            <h2>GLM Express</h2>
            <img src="{{ url_for('static', filename='research/GLMX.png') }}">
            <p>
                Developed during my time at the <a href="https://www.ssnl.stanford.edu"><b>Stanford Social Neuroscience
                        Lab</b></a>, this Python package provides a general wrapper for basic individual and group-level
                fMRI Generalized Linear Models. This package is built on <a
                    href="https://nilearn.github.io/stable/index.html">Nilearn</a>, and is optimized to work on any BIDS
                validated project.
            </p>
            <a href="https://github.com/IanRFerguson/glm-express" target="_blank">
                <p><b>View on Github</b></p>
            </a>

        </div>

        <!-- NYU Master's Thesis -->
        <div class="ac_project_box">
            <h2>NYU Master's Thesis</h2>
            <h4>
                <i>Assessing Predictors of Threat Perception in Mixed-Race Groups</i>
            </h4>
            <img src="{{ url_for('static', filename='research/thesis.png') }}">
            <p>
                Developed under the direction of Dr. Jon Freeman and Dr. DongWon Oh, this project explored the cognitive
                effects of
                status threat in non-Hispanic white social targets. After a threat prime, participants rated
                ensembles of mixed-race groups on several dimensions. A GEE model offered evidence for a linear trend,
                such that as the
                number of Hispanic social targets increased the group was rated as more threatening.
            </p>
            <a href="https://github.com/IanRFerguson/nyu-thesis" target="_blank">
                <p><b>View on Github</b></p>
            </a>
            <a href="https://drive.google.com/file/d/1L7G3iU2ldK4k4XYQ6jvOPC88zT1LMdg6/view?usp=share_link"
                target="_blank">
                <p><b>Read the Manuscript</b></p>
            </a>
        </div>

        <!-- Census Project -->
        <!-- TBD ... -->
        <!-- Publications -->
        <!--div class="ac_project_box">
            <h2>Publications</h2>
            <h2>Conference Presentations</h2>
        </div-->
    </div>

    {% endblock %}
</body>

</html>

app/templates/base.html
<html lange="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Favicon -->
    <link rel="icon" type="icon/png" href="{{ url_for('static', filename='images/noggin.png') }}">

    <!--- Bootstrap CSS --->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Custom CSS-->
    {% block styles %}
    {% endblock %}

    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='animations.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='mobile.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='logs.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='new_york.css') }}">

    <title>
        {% block title %}
        {% if title %}
        {{ title }} -
        {% else %}
        Ian Richard Ferguson, M.A.
        {% endif %}
        {% endblock %}
    </title>

</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('main.index') }}" style="font-size: 185%;">
            Ian Richard Ferguson, M.A.
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse ml-auto" id="navbarSupportedContent">
            <li class="nav-item">
                <a clas="navbar-link" href="{{ url_for('main.academics') }}">Academic Work</a>
            </li>
            <!--li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Project Portfolio
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Miles Tracker</a>
                </div>
            </li-->
        </div>
    </nav>

    <!-- Flashed messages-->
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class='alert alert-info' role='alert'>{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <!-- Custom content -->
    {% block content %}
    {% endblock %}

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>

    <!-- Custom scripts -->
    {% block scripts %}
    {% endblock %}

</body>

</html>

app/templates/food_diary/entry.html
{% extends "base.html" %}

<body>
    {% block content %}
    <div class="entry_box">
        <h2>Food Log for {{ clean_day }}</h2>
        <a href="{{ url_for('food.fd_landing') }}">
            <h4>Back to All Entries</h4>
        </a>
    </div>
    <div class="entry_box">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Food Item</th>
                    <th>Daily Count</th>
                </tr>
            </thead>
            <tbody>
                {% for k, m in items %}
                <tr>
                    <td>{{ k }}</td>
                    <td>{{ m }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endblock %}
</body>

app/templates/food_diary/index.html
{% extends "base.html" %}

<body>
    {% block content %}
    <div class="entry_box">
        <h1>Ian's Food Diary</h1>
        <h3>Taking care of your body is cool and good</h3>
    </div>

    <div class="entry_box">
        <ul>
            <li>
                <a href="{{ url_for('food.log_all_days') }}" class="entry_display">View All Logs</a>
            </li>
            {% for entry in entries %}
            <li>
                <a href="{{ url_for('food.log', date_stamp=entry) }}" class="entry_display">{{ entry }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endblock %}
</body>

app/templates/housing/index.html
{% extends "base.html" %}

<body>
    {% block content %}
    <div class="entry_box">
        <h1>Wherever You Are</h1>
    </div>
    <div class="hotspot_map">
        <iframe src="{{ url_for('global.global_map') }}"></iframe>
    </div>

    {% endblock %}
</body>

app/templates/index.html
<html lang="en">
{% extends "base.html" %}

<body>
      {% block content %}
      <div class="wrapper">
            <div class="index_box">
                  <div class="index_left">
                        <img src="{{ url_for('static', filename='images/ian_old.jpg') }}" class="howdy_ian">
                  </div>
                  <div class="index_right">
                        <div class="about_me_content">
                              <h2 style="padding-top: 35px;">
                                    <b>Howdy! I'm Ian
                                    </b>
                              </h2>
                              <ul style="about_me_box">
                                    <li class="about_me_list">
                                          🗽 I'm a developer based in New York
                                    </li>
                                    <li class="about_me_list">
                                          🗳️ I develop data pipelines, tools, and applications to help progressive
                                          political organizations build power
                                    </li>
                                    <li class="about_me_list">
                                          🧠 I'm a former academic and love learning about novel ways to model the
                                          social
                                          brain!
                                    </li>
                                    <li class="about_me_list">
                                          🏀 My other passions include thinking long and hard about the New York
                                          Knickerbockers
                                          and <a href="https://www.instagram.com/human_cactus/" target="_blank"">photographing the world around me</a>
                                    </li>
                              </ul>
                        </div>
                        <div class=" contact_me_content">
                                                <h4>Connect With Me</h4>
                                                <ul class="contact_me_icons">
                                                      <!-- Github -->
                                                      <a href="https://github.com/IanRFerguson" target="_blank">
                                                            <img src="{{ url_for('static', filename='social/bold_git.png') }}"
                                                                  class="contact_button">
                                                      </a>

                                                      <!-- Twitter -->
                                                      <a href="https://twitter.com/human_cactus" target="_blank">
                                                            <img src="{{ url_for('static', filename='social/bold_twitter.png') }}"
                                                                  class="contact_button">
                                                      </a>

                                                      <!-- LinkedIn -->
                                                      <a href="https://www.linkedin.com/in/ianrferguson/"
                                                            target="_blank">
                                                            <img src="{{ url_for('static', filename='social/bold_linkedin.svg') }}"
                                                                  class="contact_button">
                                                      </a>
                                                </ul>

                        </div>
                  </div>
            </div>
            <!-- Footer -->
            <footer class="footer" id="thanks">
                  <p>
                        Made with ❤️ in San Francisco
                  </p>
            </footer>
      </div>
      {% endblock %}

      {% block scripts %}
      <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>

      <script>
            $(document).ready(function () {
                  $('#navbarNav').collapse();
            });
      </script>
      <script src="{{ url_for('static', filename='ripper.js') }}"></script>
      {% endblock %}
</body>

</html>

app/templates/new_york/add.html
{% extends 'new_york/base.html' %}

<body>
    {% block content %}

    <div class="add_box">
        <h4>Add a New Hotspot</h4>
    </div>

    <div class="add_box">
        <form action="{{ url_for('new_york.add') }}" method="POST" class="intake_form">
            <div class="add_box">
                <label for="venue_name">Venue Name</label>
                <br>
                <input type="text" id="venue_name" name="venue_name">
            </div>

            <div class="add_box">
                <label for="street_address">Street Address</label>
                <br>
                <input type="text" id="street_address" name="street_address">
            </div>

            <div class="add_box">
                <label for="city">City</label>
                <br>
                <input type="text" id="city" name="city">
            </div>

            <div class="add_box">
                <label for="venue_type">Venue Type</label>
                <br>
                <select name="venue_type" id="venue_type">
                    <option value="None"></option>
                    <option value="coffee">Coffee Shop</option>
                    <option value="bar">Bar / Restaurant</option>
                    <option value="hotel">Hotel Lobby</option>
                    <option value="other">Other</option>
                </select>
            </div>

            <div class="add_box">
                <label for="submitted_by">Submitted By (Optional)</label>
                <br>
                <input type="text" id="submitted_by" name="submitted_by">
            </div>

            <div class="add_box">
                <label for="comments">Comments (Optional)</label>
                <br>
                <input type="text" id="comments" name="comments">
            </div>

            <input type="submit">

        </form>
    </div>

    {% endblock %}
</body>

app/templates/new_york/base.html
<html>

<head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='new_york.css') }}">

    <!-- Icon -->
    <link>
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{{ url_for('new_york.index') }}">
            <b>NYC Wifi Hotspots</b>
        </a>
        <a class="navbar-link" href="{{ url_for('new_york.add') }}">
            Add Hotspot
        </a>
        <a class="navbar-link" href="{{ url_for('new_york.view') }}">
            View Hotspots
        </a>
        <a class="navbar-link" href="{{ url_for('new_york.upvote') }}">
            Upvote Hotspots
        </a>
        <a class="navbar-link" href="{{ url_for('main.index') }}">
            Home
        </a>
    </nav>

    <!-- Page Content -->
    {% block content %}
    {% endblock %}

    <!-- Handle messages -->
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul class="flashes">
        {% for message in messages %}
        <li>{{ messsage }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
</body>

</html>

app/templates/new_york/index.html
{% extends "new_york/base.html" %}

<body>
    {% block content %}

    <div class="hotspot_map">
        <iframe src="{{ url_for('new_york.hotspots') }}"></iframe>
    </div>

    {% endblock %}
</body>

app/templates/new_york/success.html
{% extends 'base.html' %}

<body>
    {% block content %}

    <h2>Nice one!</h2>

    <h4>
        {{ address }} has been successfully logged
    </h4>

    <a href="{{ url_for('new_york.index')}}">
        <h4>Return to Main</h4>
    </a>

    {% endblock %}
</body>

app/templates/new_york/upvote.html
{% extends 'new_york/base.html' %}

<body>
    {% block content %}

    <form action="{{ url_for('new_york.upvote') }}" method="POST">
        <label for="upvote_choice">The Wifi Here is Good:</label>
        <br>
        <select name="upvote_choice" id="upvote_choice">
            <option value=""></option>
            {% for val in data %}
            <option value="{{ val }}">{{ val }}</option>
            {% endfor %}
        </select>
        <br><br>
        <input type="submit" value="Upvote">
    </form>

    {% endblock %}
</body>

app/templates/new_york/view.html
{% extends 'base.html' %}

<body>
    {% block content %}

        <div class="view_box">
            <a href="{{ url_for('download_csv') }}">
                <h4>Download Hotspot CSV</h4>
            </a>
        </div>

        <div class="view_box">
            <table class="table table-hover">
                <thead>
                    <th>Created</th>
                    <th>Location</th>
                    <th>Address</th>
                    <th>Submitted By</th>
                    <th>Comments</th>
                    <th>Upvotes</th>
                </thead>
                <tbody>
                    {% for row in data %}
                    <tr>
                        <td>{{ row[1] }}</td>
                        <td>{{ row[5] }}</td>
                        <td>{{ row[2] }}</td>
                        <td>{{ row[-3] }}</td>
                        <td>{{ row[-2] }}</td>
                        <td>{{ row[-1] }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    {% endblock %}
</body>